---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-polo.fullname" . }}
  labels:
    {{- include "demo-polo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "demo-polo.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8010
      name: http
